### PR TITLE
Create dashing-icinga2.service

### PR DESCRIPTION
**Pull request by tachtler**
Script for systemd

### CODE REVIEW

**Comment by tachtler** [comment]
Add a script for logrotate.d as well.

**Comment by tachtler** [comment]
Hi dnsmichi,

Did you have the time to take a look on the icinag2-dashing systemd start script and the icinga2-dashing logrotate script? Maybe you can merge the two scripts into you branch?

Best regards.
Klaus.

**Comment by dnsmichi** [comment]
I'll definitely do that, thanks for the reminder.

**Comment by dnsmichi** [comment]
I've picked your patches and moved them underneath `tools`. I've further added some docs and tested the unit file inside the Vagrant box (that integration will happen soon). Everything is pushed to master now. I'll add some cosmetic changes before releasing 1.2.0.

Thanks again ❤️ 

```
[root@icinga2 ~]# mv /etc/systemd/user/dashing-icinga2.service /usr/lib/systemd/system/
[root@icinga2 ~]# systemctl daemon-reload
[root@icinga2 ~]# ps aux | grep thin
root      8529  0.0  0.0 112648   960 pts/0    S+   15:39   0:00 grep --color=auto thin
[root@icinga2 ~]# systemctl status dashing-icinga2.service
● dashing-icinga2.service - Dashing-Icinga2 host/service/network monitoring system
   Loaded: loaded (/usr/lib/systemd/system/dashing-icinga2.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
[root@icinga2 ~]# systemctl start dashing-icinga2.service
[root@icinga2 ~]# systemctl status dashing-icinga2.service
● dashing-icinga2.service - Dashing-Icinga2 host/service/network monitoring system
   Loaded: loaded (/usr/lib/systemd/system/dashing-icinga2.service; disabled; vendor preset: disabled)
   Active: active (running) since Thu 2017-04-13 15:40:08 UTC; 1s ago
  Process: 8648 ExecStart=/usr/local/bin/dashing start -d -p 8005 --pid /var/run/thin.pid (code=exited, status=0/SUCCESS)
 Main PID: 8657 (ruby)
   CGroup: /system.slice/dashing-icinga2.service
           └─8657 thin server (0.0.0.0:8005)

Apr 13 15:40:07 icinga2 systemd[1]: Starting Dashing-Icinga2 host/service/network monitoring system...
Apr 13 15:40:08 icinga2 systemd[1]: Started Dashing-Icinga2 host/service/network monitoring system.
```

**Pull request closed without merging**
