### PR TITLE
Rewrite icinga2 job

### PR DESCRIPTION
**Pull request by bodsch**
Rewrite the Job icinga2.rb
Implements a configuration Handling
Use an separated Ruby-Library for better Development

### CODE REVIEW

**Comment by dnsmichi** [comment]
https://dev.icinga.org/issues/11771

**Comment by dnsmichi** [comment]
Thanks I'll take notes from your patch when refactoring it into config file usage. I'm still undecided whether to go for json of yaml. This is also important when considering api filters defined inside the config file (e.g. top 10 hosts, or custom attribute filters).

**Comment by ronator** [comment]
Offtopic: Nice to see that 'dashing' is now re-maintained!
https://github.com/dashing-io/dashing

**Comment by dnsmichi** [comment]
Thanks, partially merged.

**Pull request closed without merging**
