### PR TITLE
Add option to show only hard state problems

### PR DESCRIPTION
**Pull request by Dambakk**
In my company we have dashing on a wall screen to show the current icinga status. However, flickering warnings and criticals became annoying and we did not find a way to make icinga not warn us until they became hard state problems. (ref question asked here: https://monitoring-portal.org/t/make-icinga-hold-back-warning-or-critical-before-reaching-hard-state/6034)

The solution was to add some logic to dashing that checks if a service or host problem is a warning or critical AND that the last hard state is not-ok, that is we have a hard state warning or critical. 

I imagine this could be useful for others too :)

### CODE REVIEW

**Comment by dnsmichi** [comment]
Thanks, it may useful to show the hard states only. I don‘t like the config option name - it is not self explainary. Also, it is not applied for the severity lists which uses a different function.

**Comment by Dambakk** [comment]
Thanks for feedback! 

I agree, do you have any suggestions for a better name? 

Yeah, we only use the meter and simplelist widgets. Which other functions need to be changed?

**Comment by dnsmichi** [comment]
`show_only_hard_states` or similar. 

The list widgets are used in combination with the severity filters. This is a hard part then - either filter the objects beforehand, or introduce a different weight for the difference between soft/hard states. Not sure which one works best.

**Comment by Dambakk** [comment]
I did the renaming 👍 

I took a look at the list widgets. E.g., for the case of services, are you talking about the `icinga-severity`-event in jobs/icinga2.rb (which calls `getServiceSeverity` in lib/icinga2.rb)? I have not used this widget before. What is the expected behavior? Here it shows all service problems, acked and not. Anyways, maybe just skip the function call to `getServiceSeverity` if the service problem is in a soft state? And same for hosts ofc.

**Comment by Dambakk** [comment]
What is the status on this PR? Will it be reviewed and merged anytime soon? @dnsmichi

**Comment by dnsmichi** [comment]
Adjusted some things.

- Renamed all variables which still include flickering
- Changed the configuration section to 'dashboard'
- Added missing support for ENV
- Added the checks to the service problem list as well, including the downtime_depth/ack checks

**Pull request merged**
