### PR TITLE
Replaced Dashing with Smashing

### PR DESCRIPTION
**Pull request by mcktr**
- migrate from Dashing to Smashing

### CODE REVIEW

**Comment by dnsmichi** [comment]
Thanks 👍  I need to look into the details how to proceed with renaming the entire project, or keeping compatibility with existing Dashing setups.

**Comment by mcktr** [comment]
I close this PR.

This was my very first PR I've every made and I am not satisfied with the changes and quality I've committed here. I will send a new PR soon that changes dashing to smashing, but I need time to dig deeper in the details.

**Comment by dnsmichi** [comment]
Oh ok :) I'm still not sure if it makes sense to switch. Are there so many enhancements in smashing to do so?

**Comment by mcktr** [comment]
I digged not very deep into dashing/smashing yet, but I think not. If I find a good reason to switch I will open an issue to discuss. :)

**Comment by dnsmichi** [comment]
That's fine for me. If those nasty cache and refresh problems would've been addressed with newer package versions, I'll happily switch too. For now it only contains some git commits for docs and tests and minor things.

One thing which came to mind - the initial dashboards where created with an older dashing version. It might be the case, that a current "regenerate" with the latest dashing binary solves some problems. I tried it once, but it entirely broke my layout and css.

**Comment by dnsmichi** [comment]
See #19 for further discussion.

**Pull request closed without merging**
