### PR TITLE
colored and sorted problems by severity

### PR DESCRIPTION
**Pull request by marconett**
screenshot 2017-08-25 12 53 25

### CODE REVIEW

**Review by bodsch — COMMENTED** [review]
nice!
but, i think, the service_problems_severity() function should be enhanced with the color.
otherwise, the loop over the function result is to  expensive.

**Comment by marconett** [comment]
i honestly wouldn't know how to do move coloring and sorting to service_problems_severity.

my branch has been working quite nicely for me for a while now. i won't redo this, so feel free to just close this pull request or work on it yourself :)

**Comment by bodsch** [comment]
Hi @marconett 
I think, i take your idea and implement this in my ruby gem.
and modify the result from the  similar function, it is possible ;)

**Comment by dnsmichi** [comment]
severity is calculated differently than just by the state. One could implement a callback which defines the sort order. I'll think about it, thanks for your patch 👍

**Comment by dnsmichi** [comment]
After a second look, I really like that patch. It doesn't affect the other lists as I feared already. 

Coloring always was a pain with that list (and that background).

**Comment by dnsmichi** [comment]
Oh, there's one problem though - that patch kills the values in a list.

**Comment by dnsmichi** [comment]
Fixed, squashed, and rebased against master. Thanks for your contribution! 👍 

screen shot 2018-01-20 at 17 14 21

**Pull request merged**
