### PR TITLE
Upgrade Presentation Layer

### PR DESCRIPTION
**Pull request by spjmurray**
It felt like too much presentation stuff was being repeated in each of the
widgets so I've moved as much of this as I can into the application css, so
you change one, you change them all.  I was slightly horrified by the absolute
positioning stuff so migrated to the far more elegant flex-box model.  Various
other cleanups and little bit of sparkle ;p

### CODE REVIEW

**Comment by spjmurray** [comment]
Here's how it looks https://incubator.storage.datacentred.io/dashing-icinga.png
Hopefully I've not gone too modern (e.g. with the standards I am using) or too distasteful (with the pimp mode stuff) for Michael :smiling_imp:

**Comment by dnsmichi** [comment]
Sweet, thanks 👍

**Comment by dnsmichi** [comment]
Fancy, I like your style a lot ❤️ 

screen shot 2017-08-22 at 09 42 04

**Comment by dnsmichi** [comment]
Top, thanks 🥇

**Pull request merged**
