### PR TITLE
Run Dashing in docker container

### PR DESCRIPTION
**Pull request by zhmurko**

### CODE REVIEW

**Comment by dnsmichi** [comment]
Thanks, but I don't want to maintain nor support a Docker image. Anyone else out there might do that in a separate repository.

**Comment by zhmurko** [comment]
👍 ok, no problem
I will keep Dockerfile in https://github.com/zhmurko/dashing-icinga2

**Comment by dnsmichi** [comment]
Ok, thanks for your understanding :)

**Comment by dnsmichi** [comment]
I've changed my mind with 1) working with GitHub actions & GItLab CI recently 2) now maintaining this for myself without Icinga relation. #85 puts everything together.

**Pull request closed without merging**
